services:
  abpsolution3-blazor:
    image: abpsolution3-blazor:latest
    container_name: abpsolution3-blazor
    build:
      context: ../../
      dockerfile: src/AbpSolution3.Blazor/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080;
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=341ab61c-fae6-4baf-9e07-8a551e53de4f
      - App__SelfUrl=https://localhost:44373
      - App__HealthCheckUrl=http://abpsolution3-blazor:8080/health-status
      - AuthServer__RequireHttpsMetadata=false      
      - AuthServer__Authority=http://abpsolution3-blazor:8080
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=AbpSolution3;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44373:8081"
    depends_on:    
      sql-server:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/app/certs
    networks:
      - abp-network

  db-migrator:
    image: abpsolution3-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/AbpSolution3.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__AbpSolution3_BlazorServerTiered__RootUrl=https://localhost:44366
      - OpenIddict__Applications__AbpSolution3_Swagger__RootUrl=https://localhost:44354
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=AbpSolution3;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/azure-sql-edge:1.0.7
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -C -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqldata:
    name: abpsolution3_sqldata
networks:
  abp-network:
    name: abpsolution3-network
    driver: bridge
